name: 'Keith & Mary G in Ukraine'
favicon: null
layout_spectrum: 0.21029
typography_spectrum: 0.7142356934491545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#454545'
    - '#989898'
    - '#c1c1c1'
    - '#fdfdfd'
  brandStrength: 0.2437115574721247
  lightness: 0.29489308991469443
  saturation: 0.6177365269977599
  rhythmicContrast: 0.7082501989789307
purpose: []
